version: 2
jobs:
 build:
    docker:
      - image: cimg/openjdk:18.0.1
    # steps:
    #   - checkout
    #   - run: java --version


    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


        # run tests!
      - run: mvn clean
      - run: mvn test
    workflows:
    maven_test:
    jobs:
      - maven/test